using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class Player_Sample : MonoBehaviour
{
    private const float copySpeed = 5;//åˆ†èº«ã®ç§»å‹•é€Ÿåº¦
    private const float jumpForce = 15;//1æ®µç›®ã®ã‚¸ãƒ£ãƒ³ãƒ—åŠ›
    private const float secondJumpForce = 11;//2æ®µç›®ã®ã‚¸ãƒ£ãƒ³ãƒ—åŠ›
    private const float maxJumpTime = 0.3f;//æœ€å¤§ã‚¸ãƒ£ãƒ³ãƒ—ã®ç§’æ•°
    private const float endSpeed = 1.0f;//æŒ‡ã‚’é›¢ã—ãŸã¨ãã®ã‚¹ãƒ”ãƒ¼ãƒ‰
    private const float reduceJumpSpeedRate = 0.3f;//ã‚¸ãƒ£ãƒ³ãƒ—ã‚’ã‚„ã‚ãŸã¨ãã®ã‚¹ãƒ”ãƒ¼ãƒ‰æ¸›å°‘ç‡
    private const float maxFallingSpeed = -10f;//æœ€å¤§è½ä¸‹é€Ÿåº¦
    private const float moveSpeed = 6;//æ¨ªç§»å‹•é€Ÿåº¦

    [SerializeField]
    private GameObject[] groundCheckObjects;
    [SerializeField]
    private GameObject[] rightWallCheckObjects;//å³ã®å£ã‚’ãƒã‚§ãƒƒã‚¯ã™ã‚‹
    [SerializeField]
    private GameObject rightDownWallCheckObject;



    private float m_MoveSpeed = 3;
    private Rigidbody2D m_RigidBody2D;
    private Transform m_Transform;
    private GameObject m_PlayerCopy;
    private SpriteRenderer m_SpriteRenderer;
    private bool m_DirectionLeft = false;//å·¦ã‚’å‘ã„ã¦ã‚Œã°true
    private float m_JumpTimer;//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Ä‚ï¿½ï¿½éï¿½ï¿½
    private bool m_IsFirstJumping;//ä¸€æ®µã‚¸ãƒ£ãƒ³ãƒ—ä¸­true
    private bool m_IsSecondJumping;//2æ®µã‚¸ãƒ£ãƒ³ãƒ—ä¸­true
    private bool m_JumpEnd;
    private bool m_isGrounded;
    private bool m_isGroundedPrev;
    private bool m_CanLeftMove;
    private bool m_CanRightMove;
    private bool m_CanSecondJump;
    private bool m_PlayerFlosen;//trueãªã‚‰æ“ä½œã‚’å—ã‘ä»˜ã‘ãªããªã‚‹ã€‚KillPlayerã®æ™‚ãªã©ã«å‘¼ã°ã‚Œã‚‹
    private PlayerStart[] m_PS;


    public float MoveSpeed
    {
        set
        {
            m_MoveSpeed = value;
            if (m_MoveSpeed < 0)
            {
                m_MoveSpeed = 0;
            }
        }
        get => m_MoveSpeed;
    }

    public bool DirectionLeft
    {
        set { m_DirectionLeft = value; }
        get => m_DirectionLeft;
    }

    public float JumpTimer
    {
        set
        {
            m_JumpTimer = value;
            if (m_JumpTimer < 0)
            {
                m_JumpTimer = 0;
            }
        }
        get => m_JumpTimer;
    }
    public bool IsFirstJumping
    {
        set { m_IsFirstJumping = value; }
        get => m_IsFirstJumping;
    }

    public bool IsSecondJumping
    {
        set { m_IsSecondJumping = value; }
        get => m_IsSecondJumping;
    }
    public bool JumpEnd
    {
        set { m_JumpEnd = value; }
        get => m_JumpEnd;
    }

    public bool IsGrounded
    {
        set { m_isGrounded = value; }
        get => m_isGrounded;
    }

    public bool IsGroundedPrev
    {
        set { m_isGroundedPrev = value; }
        get => m_isGroundedPrev;
    }

    public bool CanLeftMove
    {
        set { m_CanLeftMove = value; }
        get => m_CanLeftMove;
    }

    public bool CanRightMove
    {
        set { m_CanRightMove = value; }
        get => m_CanRightMove;
    }
    public bool CanSecondJump
    {
        set { m_CanSecondJump = value; }
        get => m_CanSecondJump;
    }
    public bool PlayerFlosen
    {
        set { m_PlayerFlosen = value; }
        get => m_PlayerFlosen;
    }
    public PlayerStart[] PS
    {
        get => m_PS;
        set { m_PS = value; }
    }



    // Start is called before the first frame update
    void Start()
    {
        Application.targetFrameRate = 50;//ãƒ•ãƒ¬ãƒ¼ãƒ ãƒ¬ãƒ¼ãƒˆã‚’50ã«
        m_RigidBody2D = this.GetComponent<Rigidbody2D>();
        m_Transform = this.transform;
        m_PlayerCopy = (GameObject)Resources.Load("Prefab/PlayerCopy");
        m_SpriteRenderer = GetComponent<SpriteRenderer>();

        int i = 0;
        PS = new PlayerStart[GameObject.FindGameObjectsWithTag("PlayerStart").Length];
        foreach(GameObject ps in GameObject.FindGameObjectsWithTag("PlayerStart"))
        {
            PS[i] = ps.GetComponent<PlayerStart>();
            i++;
        }
    }

    // Update is called once per frame
    void Update()
    {
        if (!PlayerFlosen)
        {
            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Jï¿½n
            if (Input.GetKeyDown(KeyCode.Z))
            {
                if (IsGrounded)//1æ®µã‚¸ãƒ£ãƒ³ãƒ—
                {
                    IsFirstJumping = true;
                }
                else if (!IsSecondJumping && CanSecondJump)//2æ®µã‚¸ãƒ£ãƒ³ãƒ—
                {
                    IsSecondJumping = true;
                    CanSecondJump = false;
                }
            }



            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Iï¿½ï¿½
            if (Input.GetKeyUp(KeyCode.Z))
            {
                JumpEnd = true;
            }

            CalculateJumpTime();

            //ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½
            if (Input.GetKeyDown(KeyCode.X) && GameObject.FindGameObjectsWithTag("Copy").Length == 0 && CanRightMove)
            {
                CreateCopy();
            }

            //ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
            GroundCheck();
            //ï¿½Ç‚Ì”ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
            RightWallCheck();
            //ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½sï¿½[ï¿½hï¿½ÍÅ‘ï¿½7
            CheckFallingSpeed();
        }
    }

    private void FixedUpdate()
    {
        if (!PlayerFlosen)
        {
            Jump();
            Move();
        }
    }

    //åˆ†èº«ã®ä½ç½®ã¾ã§ç§»å‹•ã™ã‚‹
    public void WarpToCopy(Vector3 pos)
    {
        m_Transform.position = pos;
        m_RigidBody2D.velocity = Vector3.zero;
        CanSecondJump = true;
    }

    private void CreateCopy()
    {

        GameObject playerCopy = Instantiate(m_PlayerCopy);


        if (DirectionLeft)
        {
            playerCopy.transform.position = m_Transform.position + Vector3.left * 0.3f;
            playerCopy.GetComponent<Rigidbody2D>().velocity = new Vector3(-copySpeed, 0, 0);
            playerCopy.GetComponent<SpriteRenderer>().flipX = true;
        }
        else
        {
            playerCopy.transform.position = m_Transform.position + Vector3.right * 0.3f;
            playerCopy.GetComponent<Rigidbody2D>().velocity = new Vector3(copySpeed, 0, 0);
        }

    }


    private void Move()
    {
        //ç§»å‹•é€Ÿåº¦è¨ˆç®—
        float x = Input.GetAxisRaw("Horizontal") * moveSpeed;

        //å£ã«è§¦ã‚Œã¦ã„ãªã„ã¨ã
        //ç§»å‹•ã™ã‚‹
        if (CanRightMove)
        {
            m_RigidBody2D.velocity = new Vector3(x, m_RigidBody2D.velocity.y);
        }
        else//å£ã«è§¦ã‚Œã¦ã„ã‚‹ã¨ã
        {
            m_RigidBody2D.velocity = new Vector3(0, m_RigidBody2D.velocity.y);
        }

        //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®å‘ãã®å¤‰æ›´
        if (x > 0)
        {
            //å¤§ãã„ãƒªãƒ•ãƒˆã«ä¹—ã£ãŸã¨ãã®ãŸã‚
            if (null == m_Transform.parent)
            {
                m_Transform.localScale = new Vector3(1, 1, 1);
            }
            else
            {
                Vector3 scale = transform.parent.lossyScale;
                m_Transform.localScale = new Vector3(1f / scale.x, 1f / scale.y, 1f / scale.z);
            }
            DirectionLeft = false;
        }
        else if (x < 0)
        {
            //å¤§ãã„ãƒªãƒ•ãƒˆã«ä¹—ã£ãŸã¨ãã®ãŸã‚
            if (null == m_Transform.parent)
            {
                m_Transform.localScale = new Vector3(-1, 1, 1);
            }
            else
            {
                Vector3 scale = transform.parent.lossyScale;
                m_Transform.localScale = new Vector3(-1f / scale.x, 1f / scale.y, 1f / scale.z);
            }
            DirectionLeft = true;
        }

    }

    private void Jump()
    {
        //1æ®µç›®ã‚¸ãƒ£ãƒ³ãƒ—
        if (IsFirstJumping)
        {
            if (0 < JumpTimer && JumpTimer < maxJumpTime && !JumpEnd)//ã‚¸ãƒ£ãƒ³ãƒ—ä¸­
            {
                //m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, 0, 0);
                m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, jumpForce * (maxJumpTime - JumpTimer) / maxJumpTime + endSpeed, 0);
            }
            else//ã‚¸ãƒ£ãƒ³ãƒ—ã‚’ã‚„ã‚ãŸã¨ã
            {
                m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, m_RigidBody2D.velocity.y * reduceJumpSpeedRate, 0);
                JumpTimer = 0;
                JumpEnd = false;
                IsFirstJumping = false;
                return;
            }
        }
        else if (IsSecondJumping)//2æ®µç›®ã‚¸ãƒ£ãƒ³ãƒ—
        {

            if (0 < JumpTimer && JumpTimer < maxJumpTime && !JumpEnd)//2æ®µç›®ã‚¸ãƒ£ãƒ³ãƒ—ä¸­
            {
                //m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, 0, 0);
                m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, secondJumpForce * (maxJumpTime - JumpTimer) / maxJumpTime + endSpeed, 0);
            }
            else//2æ®µç›®ã‚¸ãƒ£ãƒ³ãƒ—çµ‚äº†
            {
                m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, m_RigidBody2D.velocity.y * reduceJumpSpeedRate, 0);
                JumpTimer = 0;
                JumpEnd = false;
                IsSecondJumping = false;
                return;
            }
        }
        else if (JumpEnd)//è½ä¸‹ä¸­ã«æ‰‹ã‚’é›¢ã—ãŸã¨ã
        {
            JumpTimer = 0;
            JumpEnd = false;
        }



    }

    //ï¿½ï¿½ï¿½bï¿½ÔƒWï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
    private void CalculateJumpTime()
    {

        if (IsFirstJumping || IsSecondJumping)
        {
            JumpTimer += Time.deltaTime;
        }
        else if (Input.GetKeyUp(KeyCode.Z))
        {
            JumpTimer = 0;
        }


    }

    //ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½(2ï¿½iï¿½ÚƒWï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½)
    //JumpEndï¿½ï¿½falseï¿½ï¿½
    private void GroundCheck()
    {
        IsGroundedPrev = IsGrounded;
        Collider2D[] groundCheckCollider = new Collider2D[groundCheckObjects.Length];
        //ï¿½Ú’nï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½Fï¿½bï¿½N
        for (int i = 0; i < groundCheckObjects.Length; i++)
        {
            groundCheckCollider[i] = Physics2D.OverlapPoint(groundCheckObjects[i].transform.position);
            //ï¿½Ú’nï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‚ï¿½ï¿½ï¿½ï¿½A1ï¿½Â‚Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Ú’nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Æ‚ï¿½ï¿½ÄIï¿½ï¿½
            if (groundCheckCollider[i] != null && (groundCheckCollider[i].isTrigger == false || groundCheckCollider[i].CompareTag("LiftRideCheck")))
            {
                IsGrounded = true;
                CanSecondJump = true;
                JumpEnd = false;
                return;
            }
        }
        //ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Å‚ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚Í‰ï¿½ï¿½ï¿½ï¿½dï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚È‚Ì‚ÅAï¿½Ú’nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Æ”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½
        IsGrounded = false;
    }


    //å£ã®åˆ¤å®šã®ãƒã‚§ãƒƒã‚¯
    private void RightWallCheck()
    {
        //ï¿½Eï¿½ï¿½ï¿½Ì•Çƒ`ï¿½Fï¿½bï¿½N
        //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Åƒuï¿½ï¿½ï¿½bï¿½Nï¿½É‚Ô‚Â‚ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½oï¿½ï¿½Æ‚ï¿½ï¿½É‰ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚ï¿½hï¿½~ï¿½ï¿½ï¿½é‚½ï¿½ï¿½
        //ï¿½Ú’nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÍŠÖŒWï¿½È‚ï¿½
        if (!IsGrounded)
        {
            Collider2D rightDownWallCheckCollider = new Collider2D();

            rightDownWallCheckCollider = Physics2D.OverlapPoint(rightDownWallCheckObject.transform.position);

            //ï¿½uï¿½ï¿½ï¿½bï¿½Nï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Î‰Eï¿½Ésï¿½ï¿½ï¿½È‚ï¿½ï¿½B
            if (rightDownWallCheckCollider != null && rightDownWallCheckCollider.isTrigger == false)
            {
                CanRightMove = false;
                return;
            }
        }

        //ï¿½Eï¿½ï¿½ï¿½Íƒuï¿½ï¿½ï¿½bï¿½Nï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Ì‚Å‘ï¿½ï¿½ğ’²‚×‚ï¿½

        Collider2D[] rightWallCheckCollider = new Collider2D[rightWallCheckObjects.Length];
        //ï¿½Ç”ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½Fï¿½bï¿½N
        for (int i = 0; i < rightWallCheckObjects.Length; i++)
        {
            rightWallCheckCollider[i] = Physics2D.OverlapPoint(rightWallCheckObjects[i].transform.position);
            //ï¿½Ç”ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‚ï¿½ï¿½ï¿½ï¿½A1ï¿½Â‚Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½È‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ÉGï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Æ‚ï¿½ï¿½ÄIï¿½ï¿½
            if (rightWallCheckCollider[i] != null && rightWallCheckCollider[i].isTrigger == false)
            {
                CanRightMove = false;
                return;
            }
        }
        //ã“ã“ã¾ã§æ¥ã¦ã„ã‚‹ã¨è¨€ã†ã“ã¨ã¯å³ã«å£ãŒç„¡ã„ã¨ã„ã†ã“ã¨ãªã®ã§true
        CanRightMove = true;
    }

    private void CheckFallingSpeed()
    {
        if(m_RigidBody2D.velocity.y < maxFallingSpeed)
        {
            m_RigidBody2D.velocity = new Vector3(m_RigidBody2D.velocity.x, maxFallingSpeed, 0);
        }
    }

    //Killer.csã®ä»˜ã„ãŸã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã«è§¦ã‚Œã‚‹ã¨å‘¼ã°ã‚Œã‚‹
    //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚’æ“ä½œä¸èƒ½ã«ã—ã€ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚’é»’ãã™ã‚‹ã€‚ãã®å¾Œãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚’æ¶ˆå»ã—ã€å¾©æ´»ã®å‡¦ç†ã‚’ã™ã‚‹ã€‚
    public IEnumerator KillPlayer()
    {
        //å‹•ã‘ãªãã™ã‚‹
        m_RigidBody2D.gravityScale = 0;
        m_RigidBody2D.velocity = Vector3.zero;
        PlayerFlosen = true;

        //åˆ†èº«ãŒå±…ã‚‹ãªã‚‰åˆ†èº«ã‚’æ¶ˆã™
        GameObject copy;
        if (copy = GameObject.FindGameObjectWithTag("Copy"))
        {
            Destroy(copy);
        }

        //è‰²ã‚’é»’ãã™ã‚‹
        int dc = 2;//decreaseColor è‰²ã®æ¸›å°‘å€¤
        Color color = m_SpriteRenderer.color;
        while (m_SpriteRenderer.color.g > 0)
        {
            float dcf = dc * Time.deltaTime;//decrease color float
            color = new Color(color.r, color.g - dcf, color.b - dcf, color.a);
            m_SpriteRenderer.color = color;
            yield return null;
        }
        m_SpriteRenderer.color = new Color(255, 0, 0, color.a);


        

        //æ–°ã—ã„ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚’å‡ºã—ã¦è‡ªåˆ†ã¯æ¶ˆãˆã‚‹
        for(int i = 0;i < PS.Length; i++)
        {
            PS[i].CreatePlayer();
        }
        Destroy(this.gameObject);

        yield return null;
    }
}

